version: "3.7"

services:
  agent:
    build: .
    oom_kill_disable: true
    privileged: true
    ports:
      - 127.0.0.1:5080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
    environment:
      - NUVLABOX_API_KEY=${NUVLABOX_API_KEY}
      - NUVLABOX_API_SECRET=${NUVLABOX_API_SECRET}
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLABOX_ENGINE_VERSION=2.1.1
      - NUVLABOX_IMMUTABLE_SSH_PUB_KEY=${NUVLABOX_SSH_PUB_KEY}
      - HOST_HOME=${HOME}
      - VPN_INTERFACE_NAME=${VPN_INTERFACE_NAME:-vpn}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
      - VPN_CONFIG_EXTRA=${VPN_CONFIG_EXTRA}
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
