version: "3.7"

services:
  agent:
    build: .
    oom_kill_disable: true
    privileged: true
    ports:
      - 127.0.0.1:5080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
    environment:
      - NUVLAEDGE_API_KEY=${NUVLAEDGE_API_KEY}
      - NUVLAEDGE_API_SECRET=${NUVLAEDGE_API_SECRET}
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
      - NUVLAEDGE_ENGINE_VERSION=dev
      - NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY=${NUVLAEDGE_SSH_PUB_KEY}
      - HOST_HOME=${HOME}
      - VPN_INTERFACE_NAME=${VPN_INTERFACE_NAME:-vpn}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
      - VPN_CONFIG_EXTRA=${VPN_CONFIG_EXTRA}
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
