name: "Build IPRoute2 container"
on:
  push:
    branches:
      - 'main'

jobs:
  build-iproute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./code/agent/docker-tools/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64
          build-args: |
            GIT_BRANCH=${{ github.head_ref || github.ref_name }}
            GIT_BUILD_TIME=$(date --utc +%FT%T.%3NZ)
            GIT_COMMIT_ID=${{ github.sha }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}
            GITHUB_RUN_ID=${{ github.run_id }}
            PROJECT_URL=${{ github.server_url }}/${{ github.repository }}
            PACKAGE_NAME=${{ env.PACKAGE_NAME }}
          push: true
          tags: >
            nuvlaedge/iproute2:${{ github.head_ref || github.ref_name }},
            nuvlaedge/iproute2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max